### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by SerafimArts** [GraphQLCollege/fullstack-graphql-ru#1]
- [ ]  [Chapter 0](/manuscript/chapter-0.md): @lex111 
- [ ]  [Chapter 1](/manuscript/chapter-1.md): @SerafimArts
- [ ]  [Chapter 2](/manuscript/chapter-2.md): __Not distributed__
- [ ]  [Chapter 3](/manuscript/chapter-3.md): __Not distributed__
- [ ]  [Chapter 4](/manuscript/chapter-4.md): __Not distributed__
- [ ]  [Chapter 5](/manuscript/chapter-5.md): __Not distributed__
- [ ]  [Chapter 6](/manuscript/chapter-6.md): __Not distributed__
